spring.application.name=datedeals

spring.datasource.url=jdbc:postgresql://localhost:5432/datedealsdb

#spring.datasource.username=${POSTGRES_USER}
#spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
server.port=8080

# inside docker container. Map in docker-composer to location on server
# logging.file.name=/home/logs/log.txt
# logging.file.name=

# logging.group.all=org.springframework.web,org.hibernate,com.hemp.hemp_app,c.h.h.e
logging.level.all=INFO


# spring.mail.username=${EMAIL_USERNAME}
# spring.mail.password=${EMAIL_PASSWORD}
spring.mail.username=noreply@datedeals.co.za
spring.mail.password=Instagram@34!
spring.mail.host=smtpout.secureserver.net
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true