name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 'Dockerhub login'
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ vars.DOCKERHUB_USER }} --password-stdin
    - name: 'Build and push portal frontend'
      working-directory: portal
      run: |
        docker build -t jhayhh/hh .
        docker tag jhayhh/hh jhayhh/hh:datedeals-portal
        docker push jhayhh/hh:datedeals-portal
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Maven build
      working-directory: backend
      run: mvn --batch-mode --update-snapshots verify -DskipTests -e -X
    - name: 'Build and push backend docker'
      working-directory: backend
      run: |
        docker build -t jhayhh/hh .
        docker tag jhayhh/hh jhayhh/hh:datedeals
        docker push jhayhh/hh:datedeals
    - name: 'Setup SSH key'
      run: |
        echo "${{ secrets.AWS_PRIVATE_KEY }}" > JohanKeyPair.pem && chmod 400 JohanKeyPair.pem
    - name: 'SSH and pull'
      run: |
        ssh -o StrictHostKeyChecking=no -i "JohanKeyPair.pem" ${{ vars.AWS_USERNAME }}@${{ vars.AWS_EC2_INSTANCE }} \
        "echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ vars.DOCKERHUB_USER }} --password-stdin
        docker-compose stop -t 1
        docker-compose rm -f
        docker rmi ${{ vars.DOCKERHUB_USER }}/hh:datedeals
        docker-compose up -d --renew-anon-volumes"
